spring.application.name=backend

# 1. Konfigurasi Port Server
server.port=8081

# 2. Konfigurasi Database PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=20060721
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Konfigurasi JPA / Hibernate (Otomatis buat tabel)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true